<?php
/*
HLstatsZ - Real-time player and clan rankings and statistics
Originally HLstatsX Community Edition by Nicholas Hastings (2008–20XX)
Based on ELstatsNEO by Malte Bayer, HLstatsX by Tobias Oetzel, and HLstats by Simon Garner

HLstats > HLstatsX > HLstatsX:CE > HLStatsZ
HLstatsZ continues a long lineage of open-source server stats tools for Half-Life and Source games.
This version is released under the GNU General Public License v2 or later.

For current support and updates:
   https://snipezilla.com
   https://github.com/SnipeZilla
   https://forums.alliedmods.net/forumdisplay.php?f=156
*/
if ( !defined('IN_HLSTATS') ) { die('Do not access this file directly'); }

?>
</div>
<div style="clear:both;"></div>


<footer class="hlstats-footer">
  <div class="hlstats-footer-inner">
    <div class="hlstats-footer-top">
      <div class="hlstats-footer-meta">
        <?php
          echo 'Generated by HLstats<span class="z">Z</span> Real-Time Statistics '.$g_options['version'];
        ?>
      </div>
    </div>
  </div>
</footer>
</body>
</html>
