<?php
/*
HLstatsZ - Real-time player and clan rankings and statistics
Originally HLstatsX Community Edition by Nicholas Hastings (2008–20XX)
Based on ELstatsNEO by Malte Bayer, HLstatsX by Tobias Oetzel, and HLstats by Simon Garner

HLstats > HLstatsX > HLstatsX:CE > HLStatsZ
HLstatsZ continues a long lineage of open-source server stats tools for Half-Life and Source games.
This version is released under the GNU General Public License v2 or later.

For current support and updates:
   https://snipezilla.com
   https://github.com/SnipeZilla
   https://forums.alliedmods.net/forumdisplay.php?f=156
*/
if ( !defined('IN_HLSTATS') ) { die('Do not access this file directly'); }
	
	/*
	 * HLstats Page Header
	 * This file will be inserted at the top of every page generated by HLstats.
	 * This file can contain PHP code.
	 */
Header ('Cache-Control: no-cache');
$lastpage = isset($_SERVER['HTTP_REFERER'])?$_SERVER['HTTP_REFERER']:"";
?>
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="stylesheet" type="text/css" href="./styles/ingame.css?<?= filemtime('./styles/ingame.css') ?>">
	<title>HLstatsZ</title>
</head>
<body class="hlstats-ingame">
<div class="hlstats-header">
  <div class="hlstats-title">HLSTATS<span class="z">Z</span></div>
</div>
<div class="hlstats-contents">



