<?php
/*
HLstatsZ - Real-time player and clan rankings and statistics
Originally HLstatsX Community Edition by Nicholas Hastings (2008–20XX)
Based on ELstatsNEO by Malte Bayer, HLstatsX by Tobias Oetzel, and HLstats by Simon Garner

HLstats > HLstatsX > HLstatsX:CE > HLStatsZ
HLstatsZ continues a long lineage of open-source server stats tools for Half-Life and Source games.
This version is released under the GNU General Public License v2 or later.

For current support and updates:
   https://snipezilla.com
   https://github.com/SnipeZilla
   https://forums.alliedmods.net/forumdisplay.php?f=156
*/
if ( !defined('IN_HLSTATS') ) { die('Do not access this file directly'); }

	global $signin,$game,$mode,$selectedStyle,$theme,$realname;

	// see if they have a defined style or a new style they'd like
	$style = (isset($_COOKIE['style']) && $_COOKIE['style'] && $g_options['display_style_selector'] == 1) ? $_COOKIE['style'] : $g_options['style'];
	$style = !empty($_GET['stylesheet']) ? $_GET['stylesheet'] : $style; 
	// if they don't have one defined or the defined was is invalid use the default	
    $selectedStyle = $style;
	if ($selectedStyle !== 'default' && !file_exists('styles/themes/'.$style.'/'.$style.'.css'))
        $selectedStyle = 'default';


	// if they had one, or tried to have one, set it to whatever we resolved it to
	if (!empty($_GET['stylesheet']) || isset($_COOKIE['style']))
	{
		myCookie('style', $selectedStyle, time()+60*60*24*30);

        if (!empty($_GET['stylesheet'])) {
            $query = updateQueryKey(["stylesheet" => '']);
            $q = $query ? '?' : '';
            header('Location: ' . $_SERVER['PHP_SELF'] . $q . $query);
            exit();
        }
	}

    $theme  = $selectedStyle;
    $search = new Search('','',$game ?? '');
?>
<!DOCTYPE html>
<head>
    <link rel="stylesheet" type="text/css" href="styles/leaflet.css?<?= filemtime('styles/leaflet.css') ?>" />
    <link rel="stylesheet" type="text/css" href="styles/hlstatsz.css?<?= filemtime('styles/hlstatsz.css') ?>" />
    <?php if ($mode == "admin") { ?>
    <link rel="stylesheet" type="text/css" href="styles/admin.css?<?= filemtime('styles/admin.css') ?>" />
    <?php } ?>
    <?php if ($selectedStyle !== "default") { ?>
    <link rel="stylesheet" type="text/css" href="styles/themes/<?= htmlspecialchars($selectedStyle) ?>/<?= htmlspecialchars($selectedStyle) ?>.css?<?= filemtime('styles/themes/'.$selectedStyle.'/'.$selectedStyle.'.css') ?>" />
    <?php } ?>
    <script type="text/javascript" src="<?= INCLUDE_PATH ?>/js/hlstatsz.js?<?= filemtime(INCLUDE_PATH.'/js/hlstatsz.js') ?>"></script>
    <?php if (file_exists('styles/themes/'.$theme.'/'.$theme.'.js')) { ?>
    <script src="<?= 'styles/themes/'.htmlspecialchars($theme).'/'.htmlspecialchars($theme).'.js?'.filemtime('styles/themes/'.$theme.'/'.$theme.'.js')?>" defer></script>
    <?php } ?>
    <link rel="icon" type="image/png" sizes="256x256" href="favicon-256.png">
    <link rel="icon" type="image/png" sizes="32x32" href="favicon-32.png">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Generated by HLstatsZ Real-Time Statistics <?= $g_options['version'] ?>">
    <title><?php
	echo $g_options['sitename']; 
	if (!empty($realname) && $game && $mode != 'admin' && $mode != 'help') {
		echo ' - '.$realname;
	}
    if (!empty($mode)){
		echo ' - '.ucfirst($mode);
    }
    ?>
    </title>
    <?php if (defined('GOOGLE_ANALYTICS_ID') && !empty(GOOGLE_ANALYTICS_ID)) { ?>
    <script data-template-name="public:google_analytics" async src="https://www.googletagmanager.com/gtag/js?id=<?=GOOGLE_ANALYTICS_ID?>"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', '<?=GOOGLE_ANALYTICS_ID?>');
    </script>
    <?php } ?>
</head>
<body> 
<?php  

$currentMode = $mode ?? $game ?? '';

?>

<div class="hlstats-header">

  <!-- TOP BAR -->
  <div class="hlstats-top">
    <div class="hlstats-inner">

      <a class="hlstats-brand" href="<?= $g_options['scripturl'] ?>">
          <svg version="1.2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 8470 2002" width="198" height="45">
          	<style>
          		.s0 { fill: var(--logo-color); } 
          		.s1 { fill: var(--logo-color-z); } 
          	</style>
          	<path class="s0" d="m957 1h88v1h18v1h15v1h11v1h12v1h11v1h8v1h9v1h7v1h7v1h7v1h7v1h6v1h6v1h6v1h7v1h4v1h5v1h6v1h5v1h5v1h4v1h5v1h4v1h5v1h5v1h3v1h4v1h4v1h4v1h4v1h4v1h4v1h4v1h3v1h4v1h4v1h3v1h4v1h3v1h3v1h4v1h3v1h4v1h3v1h3v1h3v1h3v1h3v1h4v1h3v1h3v1h3v1h3v1h3v1h2v1h3v1h3v1h3v1h3v1h3v1h2v1h3v1h3v1h2v1h3v1h2v1h3v1h3v1h2v1h3v1h2v1h2v1h3v1h2v1h3v1h2v1h3v1h2v1h2v1h3v1h2v1h2v1h2v1h3v1h2v1h2v1h3v1h2v1h2v1h2v1h2v1h2v1h3v1h2v1h2v1h2v1h2v1h2v1h2v1h2v1h2v1h2v1h2v1h2v1h2v1h2v1h2v1h2v1h2v1h2v1h2v1h2v1h2v1h2v1h2v1h2v1h2v1h2v1h1v1h2v1h2v1h2v1h2v1h1v1h2v1h2v1h2v1h2v1h1v1h2v1h2v1h2v1h1v1h2v1h2v1h2v1h1v1h2v1h2v1h1v1h2v1h2v1h1v1h2v1h2v1h1v1h2v1h1v1h2v1h2v1h1v1h2v1h1v1h2v1h2v1h1v1h2v1h1v1h2v1h1v1h2v1h1v1h2v1h1v1h2v1h2v1h1v1h2v1h1v1h2v1h1v1h1v1h2v1h1v1h2v1h1v1h2v1h1v1h1v1h2v1h1v1h2v1h1v1h2v1h1v1h1v1h2v1h1v1h1v1h2v1h1v1h2v1h1v1h1v1h2v1h1v1h1v1h2v1h1v1h1v1h2v1h1v1h1v1h2v1h1v1h1v1h2v1h1v1h1v1h1v1h2v1h1v1h1v1h2v1h1v1h1v1h1v1h2v1h1v1h1v1h1v1h2v1h1v1h1v1h1v1h2v1h1v1h1v1h1v1h1v1h2v1h1v1h1v1h1v1h1v1h1v1h2v1h1v1h1v1h1v1h1v1h2v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h2v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h2v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h2v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v2h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v2h1v1h1v1h1v1h1v1h1v1h1v1h1v2h1v1h1v1h1v1h1v1h1v1h1v1h1v1h1v2h1v1h1v1h1v1h1v1h1v1h1v2h1v1h1v1h1v1h1v1h1v2h1v1h1v1h1v1h1v1h1v2h1v1h1v1h1v1h1v1h1v2h1v1h1v1h1v1h1v2h1v1h1v1h1v1h1v2h1v1h1v1h1v2h1v1h1v1h1v1h1v2h1v1h1v1h1v2h1v1h1v1h1v2h1v1h1v1h1v1h1v2h1v1h1v2h1v1h1v1h1v2h1v1h1v2h1v1h1v1h1v2h1v1h1v1h1v2h1v1h1v2h1v1h1v2h1v1h1v1h1v2h1v1h1v2h1v1h1v2h1v1h1v2h1v1h1v2h1v1h1v2h1v1h1v2h1v1h1v2h1v1h1v2h1v1h1v2h1v1h1v2h1v2h1v1h1v2h1v1h1v2h1v2h1v1h1v2h1v1h1v2h1v2h1v1h1v2h1v2h1v1h1v2h1v2h1v1h1v2h1v2h1v1h1v2h1v2h1v2h1v1h1v2h1v2h1v2h1v1h1v2h1v2h1v2h1v2h1v1h1v2h1v2h1v2h1v2h1v2h1v1h1v2h1v2h1v2h1v2h1v2h1v2h1v2h1v2h1v2h1v2h1v2h1v2h1v2h1v2h1v2h1v2h1v2h1v2h1v2h1v2h1v2h1v2h1v2h1v3h1v2h1v2h1v2h1v2h1v2h1v3h1v2h1v2h1v2h1v3h1v2h1v2h1v3h1v2h1v2h1v3h1v2h1v3h1v2h1v2h1v3h1v2h1v3h1v2h1v3h1v3h1v2h1v3h1v2h1v3h1v3h1v2h1v3h1v3h1v3h1v3h1v3h1v2h1v3h1v3h1v3h1v3h1v3h1v3h1v3h1v3h1v3h1v4h1v3h1v3h1v4h1v3h1v3h1v4h1v3h1v4h1v4h1v3h1v4h1v4h1v3h1v4h1v4h1v4h1v5h1v4h1v4h1v4h1v5h1v4h1v5h1v5h1v4h1v6h1v5h1v5h1v5h1v6h1v6h1v6h1v6h1v7h1v7h1v7h1v7h1v9h1v9h1v9h1v12h1v11h1v15h1v20h1v86h-1v20h-1v15h-1v11h-1v12h-1v9h-1v9h-1v8h-1v8h-1v7h-1v7h-1v7h-1v6h-1v6h-1v6h-1v6h-1v5h-1v5h-1v5h-1v6h-1v4h-1v5h-1v5h-1v4h-1v5h-1v4h-1v4h-1v4h-1v5h-1v4h-1v4h-1v4h-1v3h-1v4h-1v4h-1v3h-1v4h-1v4h-1v3h-1v4h-1v3h-1v3h-1v4h-1v3h-1v3h-1v4h-1v3h-1v3h-1v3h-1v3h-1v3h-1v3h-1v3h-1v3h-1v3h-1v2h-1v3h-1v3h-1v3h-1v3h-1v2h-1v3h-1v3h-1v2h-1v3h-1v3h-1v2h-1v3h-1v3h-1v2h-1v3h-1v2h-1v3h-1v2h-1v2h-1v3h-1v2h-1v3h-1v2h-1v2h-1v3h-1v2h-1v2h-1v3h-1v2h-1v2h-1v2h-1v2h-1v3h-1v2h-1v2h-1v2h-1v2h-1v3h-1v2h-1v2h-1v2h-1v2h-1v2h-1v2h-1v2h-1v2h-1v2h-1v2h-1v2h-1v2h-1v2h-1v2h-1v2h-1v2h-1v2h-1v2h-1v2h-1v2h-1v2h-1v2h-1v2h-1v1h-1v2h-1v2h-1v2h-1v2h-1v2h-1v1h-1v2h-1v2h-1v2h-1v2h-1v1h-1v2h-1v2h-1v2h-1v1h-1v2h-1v2h-1v2h-1v1h-1v2h-1v2h-1v1h-1v2h-1v2h-1v1h-1v2h-1v2h-1v1h-1v2h-1v2h-1v1h-1v2h-1v1h-1v2h-1v2h-1v1h-1v2h-1v1h-1v2h-1v2h-1v1h-1v2h-1v1h-1v2h-1v1h-1v2h-1v1h-1v2h-1v1h-1v2h-1v1h-1v2h-1v1h-1v2h-1v1h-1v2h-1v1h-1v2h-1v1h-1v2h-1v1h-1v1h-1v2h-1v1h-1v2h-1v1h-1v2h-1v1h-1v1h-1v2h-1v1h-1v1h-1v2h-1v1h-1v1h-1v2h-1v1h-1v2h-1v1h-1v1h-1v2h-1v1h-1v1h-1v2h-1v1h-1v1h-1v1h-1v2h-1v1h-1v1h-1v2h-1v1h-1v1h-1v2h-1v1h-1v1h-1v2h-1v1h-1v1h-1v1h-1v2h-1v1h-1v1h-1v1h-1v1h-1v2h-1v1h-1v1h-1v1h-1v2h-1v1h-1v1h-1v1h-1v1h-1v2h-1v1h-1v1h-1v1h-1v1h-1v2h-1v1h-1v1h-1v1h-1v1h-1v1h-1v2h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v2h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v2h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v2h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-2v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-2v2h-2v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-2v1h-1v1h-1v1h-1v1h-1v1h-1v1h-2v2h-2v1h-1v1h-1v1h-1v1h-1v1h-2v1h-1v1h-1v1h-1v1h-1v1h-1v1h-2v1h-1v1h-1v1h-1v1h-1v1h-2v1h-1v1h-1v1h-1v1h-2v1h-1v1h-1v1h-1v1h-2v1h-1v1h-1v1h-1v1h-2v1h-1v1h-1v1h-2v1h-1v1h-1v1h-1v1h-2v1h-1v1h-1v1h-2v1h-1v1h-1v1h-2v1h-1v1h-2v1h-1v1h-1v1h-1v1h-2v1h-1v1h-1v1h-2v1h-1v1h-2v1h-1v1h-1v1h-2v1h-1v1h-2v1h-1v1h-1v1h-2v1h-1v1h-2v1h-1v1h-1v1h-2v1h-1v1h-2v1h-1v1h-2v1h-1v1h-2v1h-1v1h-1v1h-2v1h-1v1h-2v1h-2v1h-1v1h-2v1h-1v1h-2v1h-1v1h-2v1h-1v1h-2v1h-1v1h-2v1h-2v1h-1v1h-2v1h-1v1h-2v1h-2v1h-1v1h-2v1h-1v1h-2v1h-2v1h-1v1h-2v1h-2v1h-1v1h-2v1h-2v1h-1v1h-2v1h-2v1h-2v1h-1v1h-2v1h-2v1h-2v1h-1v1h-2v1h-2v1h-2v1h-2v1h-1v1h-2v1h-2v1h-2v1h-2v1h-1v1h-2v1h-2v1h-2v1h-2v1h-2v1h-2v1h-2v1h-2v1h-2v1h-2v1h-2v1h-2v1h-2v1h-2v1h-2v1h-2v1h-2v1h-2v1h-2v1h-2v1h-2v1h-2v1h-2v1h-2v1h-2v1h-3v1h-2v1h-2v1h-2v1h-2v1h-2v1h-3v1h-2v1h-2v1h-3v1h-2v1h-2v1h-2v1h-3v1h-2v1h-2v1h-3v1h-2v1h-3v1h-2v1h-3v1h-2v1h-2v1h-3v1h-2v1h-3v1h-3v1h-2v1h-3v1h-2v1h-3v1h-3v1h-2v1h-3v1h-3v1h-3v1h-3v1h-3v1h-2v1h-3v1h-3v1h-3v1h-3v1h-3v1h-4v1h-3v1h-3v1h-3v1h-3v1h-3v1h-4v1h-3v1h-4v1h-3v1h-3v1h-4v1h-3v1h-4v1h-4v1h-3v1h-4v1h-4v1h-4v1h-4v1h-4v1h-4v1h-4v1h-4v1h-4v1h-5v1h-4v1h-5v1h-5v1h-4v1h-5v1h-6v1h-5v1h-5v1h-6v1h-6v1h-6v1h-7v1h-6v1h-7v1h-7v1h-7v1h-9v1h-10v1h-9v1h-12v1h-11v1h-15v1h-18v1h-88v-1h-18v-1h-15v-1h-11v-1h-12v-1h-9v-1h-10v-1h-9v-1h-7v-1h-7v-1h-7v-1h-6v-1h-7v-1h-6v-1h-6v-1h-6v-1h-5v-1h-5v-1h-6v-1h-5v-1h-4v-1h-5v-1h-5v-1h-4v-1h-5v-1h-4v-1h-4v-1h-4v-1h-4v-1h-4v-1h-4v-1h-4v-1h-4v-1h-4v-1h-3v-1h-4v-1h-4v-1h-3v-1h-4v-1h-3v-1h-3v-1h-4v-1h-3v-1h-4v-1h-3v-1h-3v-1h-3v-1h-3v-1h-3v-1h-4v-1h-3v-1h-3v-1h-3v-1h-3v-1h-3v-1h-2v-1h-3v-1h-3v-1h-3v-1h-3v-1h-3v-1h-2v-1h-3v-1h-3v-1h-2v-1h-3v-1h-2v-1h-3v-1h-3v-1h-2v-1h-3v-1h-2v-1h-2v-1h-3v-1h-2v-1h-3v-1h-2v-1h-3v-1h-2v-1h-2v-1h-3v-1h-2v-1h-2v-1h-2v-1h-3v-1h-2v-1h-2v-1h-3v-1h-2v-1h-2v-1h-2v-1h-2v-1h-2v-1h-3v-1h-2v-1h-2v-1h-2v-1h-2v-1h-2v-1h-2v-1h-2v-1h-2v-1h-2v-1h-2v-1h-2v-1h-2v-1h-2v-1h-2v-1h-2v-1h-2v-1h-2v-1h-2v-1h-2v-1h-2v-1h-2v-1h-2v-1h-2v-1h-2v-1h-2v-1h-1v-1h-2v-1h-2v-1h-2v-1h-2v-1h-1v-1h-2v-1h-2v-1h-2v-1h-2v-1h-1v-1h-2v-1h-2v-1h-2v-1h-1v-1h-2v-1h-2v-1h-2v-1h-1v-1h-2v-1h-2v-1h-1v-1h-2v-1h-2v-1h-1v-1h-2v-1h-2v-1h-1v-1h-2v-1h-1v-1h-2v-1h-2v-1h-1v-1h-2v-1h-2v-1h-1v-1h-2v-1h-1v-1h-2v-1h-1v-1h-2v-1h-1v-1h-2v-1h-1v-1h-2v-1h-1v-1h-2v-1h-2v-1h-1v-1h-2v-1h-1v-1h-1v-1h-2v-1h-1v-1h-2v-1h-1v-1h-2v-1h-1v-1h-2v-1h-1v-1h-1v-1h-2v-1h-1v-1h-2v-1h-1v-1h-1v-1h-2v-1h-1v-1h-2v-1h-1v-1h-1v-1h-2v-1h-1v-1h-2v-1h-1v-1h-1v-1h-2v-1h-1v-1h-1v-1h-2v-1h-1v-1h-1v-1h-2v-1h-1v-1h-1v-1h-2v-1h-1v-1h-1v-1h-2v-1h-1v-1h-1v-1h-1v-1h-2v-1h-1v-1h-1v-1h-2v-1h-1v-1h-1v-1h-1v-1h-2v-1h-1v-1h-1v-1h-1v-1h-2v-1h-1v-1h-1v-1h-1v-1h-2v-1h-1v-1h-1v-1h-1v-1h-1v-1h-2v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-2v-1h-1v-1h-1v-1h-1v-1h-1v-1h-2v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-2v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-2v-2h-2v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-2v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-2h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-2h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-2h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-2h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-2h-1v-1h-1v-1h-1v-1h-1v-1h-1v-2h-1v-1h-1v-1h-1v-1h-1v-1h-1v-2h-1v-1h-1v-1h-1v-1h-1v-1h-1v-2h-1v-1h-1v-1h-1v-1h-1v-2h-1v-1h-1v-1h-1v-1h-1v-2h-1v-1h-1v-1h-1v-2h-1v-1h-1v-1h-1v-2h-1v-1h-1v-1h-1v-1h-1v-2h-1v-1h-1v-1h-1v-2h-1v-1h-1v-1h-1v-2h-1v-1h-1v-1h-1v-2h-1v-1h-1v-2h-1v-1h-1v-1h-1v-2h-1v-1h-1v-1h-1v-2h-1v-1h-1v-1h-1v-2h-1v-1h-1v-2h-1v-1h-1v-2h-1v-1h-1v-1h-1v-2h-1v-1h-1v-2h-1v-1h-1v-2h-1v-1h-1v-2h-1v-1h-1v-2h-1v-1h-1v-2h-1v-1h-1v-2h-1v-1h-1v-2h-1v-1h-1v-2h-1v-1h-1v-2h-1v-1h-1v-2h-1v-2h-1v-1h-1v-2h-1v-1h-1v-2h-1v-2h-1v-1h-1v-2h-1v-1h-1v-2h-1v-2h-1v-1h-1v-2h-1v-2h-1v-1h-1v-2h-1v-2h-1v-1h-1v-2h-1v-2h-1v-1h-1v-2h-1v-2h-1v-2h-1v-1h-1v-2h-1v-2h-1v-2h-1v-1h-1v-2h-1v-2h-1v-2h-1v-2h-1v-1h-1v-2h-1v-2h-1v-2h-1v-2h-1v-2h-1v-1h-1v-2h-1v-2h-1v-2h-1v-2h-1v-2h-1v-2h-1v-2h-1v-2h-1v-2h-1v-2h-1v-2h-1v-2h-1v-2h-1v-2h-1v-2h-1v-2h-1v-2h-1v-2h-1v-2h-1v-2h-1v-2h-1v-2h-1v-2h-1v-3h-1v-2h-1v-2h-1v-2h-1v-2h-1v-3h-1v-2h-1v-2h-1v-2h-1v-2h-1v-3h-1v-2h-1v-2h-1v-3h-1v-2h-1v-2h-1v-3h-1v-2h-1v-3h-1v-2h-1v-2h-1v-3h-1v-2h-1v-3h-1v-2h-1v-3h-1v-3h-1v-2h-1v-3h-1v-3h-1v-2h-1v-3h-1v-3h-1v-2h-1v-3h-1v-3h-1v-3h-1v-3h-1v-2h-1v-3h-1v-3h-1v-3h-1v-3h-1v-3h-1v-3h-1v-3h-1v-3h-1v-3h-1v-4h-1v-3h-1v-3h-1v-4h-1v-3h-1v-3h-1v-4h-1v-3h-1v-4h-1v-4h-1v-3h-1v-4h-1v-4h-1v-3h-1v-4h-1v-4h-1v-4h-1v-5h-1v-4h-1v-4h-1v-4h-1v-5h-1v-4h-1v-5h-1v-5h-1v-4h-1v-6h-1v-5h-1v-5h-1v-5h-1v-6h-1v-6h-1v-6h-1v-6h-1v-7h-1v-7h-1v-7h-1v-8h-1v-8h-1v-9h-1v-9h-1v-12h-1v-11h-1v-15h-1v-20h-1v-86h1v-20h1v-15h1v-11h1v-12h1v-9h1v-9h1v-9h1v-7h1v-7h1v-7h1v-7h1v-6h1v-6h1v-6h1v-6h1v-5h1v-5h1v-5h1v-6h1v-4h1v-5h1v-5h1v-4h1v-5h1v-4h1v-4h1v-4h1v-5h1v-4h1v-4h1v-4h1v-3h1v-4h1v-4h1v-3h1v-4h1v-4h1v-3h1v-4h1v-3h1v-3h1v-4h1v-3h1v-3h1v-4h1v-3h1v-3h1v-3h1v-3h1v-3h1v-3h1v-3h1v-3h1v-3h1v-3h1v-2h1v-3h1v-3h1v-3h1v-3h1v-2h1v-3h1v-3h1v-2h1v-3h1v-2h1v-3h1v-3h1v-2h1v-3h1v-2h1v-3h1v-2h1v-2h1v-3h1v-2h1v-3h1v-2h1v-2h1v-3h1v-2h1v-2h1v-3h1v-2h1v-2h1v-2h1v-3h1v-2h1v-2h1v-2h1v-2h1v-2h1v-3h1v-2h1v-2h1v-2h1v-2h1v-2h1v-2h1v-2h1v-2h1v-2h1v-2h1v-2h1v-2h1v-2h1v-2h1v-2h1v-2h1v-2h1v-2h1v-2h1v-2h1v-2h1v-2h1v-2h1v-1h1v-2h1v-2h1v-2h1v-2h1v-2h1v-1h1v-2h1v-2h1v-2h1v-2h1v-1h1v-2h1v-2h1v-2h1v-1h1v-2h1v-2h1v-2h1v-1h1v-2h1v-2h1v-1h1v-2h1v-2h1v-1h1v-2h1v-2h1v-1h1v-2h1v-2h1v-1h1v-2h1v-1h1v-2h1v-2h1v-1h1v-2h1v-1h1v-2h1v-2h1v-1h1v-2h1v-1h1v-2h1v-1h1v-2h1v-1h1v-2h1v-1h1v-2h1v-1h1v-2h1v-1h1v-2h1v-1h1v-2h1v-1h1v-2h1v-1h1v-2h1v-1h1v-1h1v-2h1v-1h1v-2h1v-1h1v-2h1v-1h1v-1h1v-2h1v-1h1v-1h1v-2h1v-1h1v-2h1v-1h1v-1h1v-2h1v-1h1v-2h1v-1h1v-1h1v-1h1v-2h1v-1h1v-1h1v-2h1v-1h1v-1h1v-2h1v-1h1v-1h1v-1h1v-2h1v-1h1v-1h1v-2h1v-1h1v-1h1v-1h1v-2h1v-1h1v-1h1v-1h1v-2h1v-1h1v-1h1v-1h1v-1h1v-2h1v-1h1v-1h1v-1h1v-1h1v-2h1v-1h1v-1h1v-1h1v-1h1v-2h1v-1h1v-1h1v-1h1v-1h1v-1h1v-2h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-2h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-2h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-2h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h2v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h2v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h2v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h2v-1h1v-1h1v-1h1v-1h1v-1h2v-1h1v-1h1v-1h1v-1h1v-1h1v-1h2v-1h1v-1h1v-1h1v-1h1v-1h2v-1h1v-1h1v-1h1v-1h2v-1h1v-1h1v-1h1v-1h2v-1h1v-1h1v-1h1v-1h2v-1h1v-1h1v-1h2v-1h1v-1h1v-1h1v-1h2v-1h1v-1h1v-1h2v-1h1v-1h1v-1h2v-1h1v-1h1v-1h2v-1h1v-1h1v-1h2v-1h1v-1h1v-1h2v-1h1v-1h2v-1h1v-1h1v-1h2v-1h1v-1h1v-1h2v-1h1v-1h2v-1h1v-1h2v-1h1v-1h1v-1h2v-1h1v-1h2v-1h1v-1h2v-1h1v-1h1v-1h2v-1h1v-1h2v-1h1v-1h2v-1h2v-1h1v-1h2v-1h1v-1h2v-1h1v-1h2v-1h1v-1h2v-1h1v-1h2v-1h2v-1h1v-1h2v-1h1v-1h2v-1h2v-1h1v-1h2v-1h1v-1h2v-1h2v-1h1v-1h2v-1h2v-1h1v-1h2v-1h2v-1h1v-1h2v-1h2v-1h2v-1h1v-1h2v-1h2v-1h2v-1h1v-1h2v-1h2v-1h2v-1h2v-1h1v-1h2v-1h2v-1h2v-1h2v-1h1v-1h2v-1h2v-1h2v-1h2v-1h2v-1h2v-1h2v-1h2v-1h2v-1h2v-1h2v-1h2v-1h2v-1h2v-1h2v-1h2v-1h2v-1h2v-1h2v-1h2v-1h2v-1h2v-1h2v-1h2v-1h2v-1h3v-1h2v-1h2v-1h2v-1h2v-1h2v-1h3v-1h2v-1h2v-1h3v-1h2v-1h2v-1h2v-1h3v-1h2v-1h2v-1h3v-1h2v-1h3v-1h2v-1h3v-1h2v-1h2v-1h3v-1h2v-1h3v-1h3v-1h2v-1h3v-1h2v-1h3v-1h3v-1h2v-1h3v-1h3v-1h3v-1h3v-1h3v-1h2v-1h3v-1h3v-1h3v-1h3v-1h3v-1h4v-1h3v-1h3v-1h3v-1h3v-1h3v-1h4v-1h3v-1h4v-1h3v-1h3v-1h4v-1h3v-1h4v-1h4v-1h3v-1h4v-1h4v-1h4v-1h4v-1h4v-1h4v-1h4v-1h3v-1h5v-1h5v-1h4v-1h5v-1h4v-1h5v-1h5v-1h6v-1h5v-1h4v-1h7v-1h6v-1h6v-1h6v-1h7v-1h7v-1h7v-1h7v-1h9v-1h8v-1h11v-1h12v-1h11v-1h15v-1h18zm116 329v2h-2v893h1v1h274v-894h-1v-2zm-360 286v607h275v-607zm-381 223v1h-2v740h2v1h2v1h1105v89h6v-2h2v-2h1v-1h1v-1h1v-1h2v-2h1v-1h2v-2h2v-2h1v-1h2v-2h1v-1h2v-2h2v-2h1v-1h2v-2h1v-1h1v-1h1v-1h2v-2h1v-1h2v-2h1v-1h1v-1h1v-1h2v-2h1v-1h2v-2h1v-1h1v-1h1v-1h2v-2h1v-1h2v-2h1v-1h1v-1h1v-1h2v-2h1v-1h2v-2h1v-1h1v-1h1v-1h2v-2h1v-1h2v-2h1v-1h1v-1h1v-1h2v-2h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h2v-2h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h2v-2h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h2v-2h1v-1h1v-1h1v-1h2v-2h1v-1h2v-2h1v-1h1v-1h1v-1h2v-2h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h2v-2h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h2v-2h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h2v-2h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h2v-2h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-7h-2v-1h-1v-2h-2v-2h-1v-1h-2v-2h-2v-1h-1v-2h-2v-2h-1v-1h-2v-2h-2v-1h-1v-2h-2v-2h-1v-1h-2v-2h-2v-2h-1v-1h-2v-2h-1v-1h-2v-2h-2v-2h-1v-1h-2v-2h-1v-1h-2v-2h-2v-2h-1v-1h-2v-2h-1v-1h-2v-2h-2v-2h-1v-1h-2v-2h-1v-1h-2v-2h-2v-2h-1v-1h-2v-2h-1v-1h-1v-1h-1v-1h-2v-3h-3v-2h-1v-1h-1v-1h-1v-1h-2v-3h-3v-2h-1v-1h-1v-2h-3v-3h-3v-2h-1v-1h-1v-2h-3v-3h-3v-2h-1v-1h-1v-2h-3v-3h-2v-1h-1v-1h-1v-1h-1v-2h-2v-1h-1v-2h-2v-2h-2v-1h-1v-2h-2v-1h-1v-2h-2v-2h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-2h-2v-1h-1v-2h-2v-2h-2v-1h-1v-2h-2v-1h-1v-2h-2v-2h-2v-1h-1v-2h-2v-2h-1v-1h-2v-2h-1v-1h-2v-2h-2v-2h-1v-1h-2v-2h-1v-1h-1v-1h-1v-1h-2v-2h-1v-1h-2v-2h-1v-1h-1v-1h-1v-1h-2v-2h-1v-1h-2v-2h-1v-1h-1v-1h-1v-1h-2v-2h-1v-1h-1v-1h-1v-1h-1v-1h-1v-2h-3v-3h-2v-1h-1v-1h-1v-1h-1v-2h-3v-3h-2v-1h-1v-1h-1v-1h-1v-2h-2v-1h-1v-2h-2v-2h-2v-1h-1v-2h-2v-1h-1v-2h-2v-1h-1v-1h-3v1h-1v94h-832v-467z"/>
          	<path id="HLSTATSZ" class="s0" aria-label="HLSTATSZ"  d="m3249.6 1464v-925.6h-180.7v378.3h-313.3v-378.3h-180.7v925.6h180.7v-387.4h313.3v387.4zm815.9 0v-161.2h-419.9v-764.4h-180.7v925.6zm745.4-273c0-81.9-22.1-149.5-71.5-196.3-39-36.4-92.3-59.8-176.8-71.5l-109.2-15.6c-37.7-5.2-67.6-19.5-85.8-36.4-19.5-18.2-27.3-42.9-27.3-66.3 0-63.7 46.8-117 143-117 61.1 0 131.3 7.8 189.8 63.7l114.4-113.1c-79.3-76.7-171.6-107.9-299-107.9-200.2 0-322.4 115.7-322.4 280.8 0 78 22.1 137.8 66.3 182 41.6 40.3 100.1 65 179.4 76.7l111.8 15.6c42.9 6.5 63.7 15.6 81.9 32.5 19.5 18.2 28.6 45.5 28.6 78 0 74.1-57.2 114.4-163.8 114.4-85.8 0-165.1-19.5-223.6-78l-117 117c91 92.3 197.6 122.2 338 122.2 193.7 0 343.2-101.4 343.2-280.8zm765.4-491.4v-161.2h-664.3v161.2h241.8v764.4h180.7v-764.4zm784.6 764.4l-338-925.6h-141.7l-336.7 925.6h188.5l55.9-163.8h328.9l54.6 163.8zm-291.2-315.9h-230.1l117-336.7zm922.6-448.5v-161.2h-664.3v161.2h241.8v764.4h180.7v-764.4zm744.6 491.4c0-81.9-22.1-149.5-71.5-196.3-39-36.4-92.3-59.8-176.8-71.5l-109.2-15.6c-37.7-5.2-67.6-19.5-85.8-36.4-19.5-18.2-27.3-42.9-27.3-66.3 0-63.7 46.8-117 143-117 61.1 0 131.3 7.8 189.8 63.7l114.4-113.1c-79.3-76.7-171.6-107.9-299-107.9-200.2 0-322.4 115.7-322.4 280.8 0 78 22.1 137.8 66.3 182 41.6 40.3 100.1 65 179.4 76.7l111.8 15.6c42.9 6.5 63.7 15.6 81.9 32.5 19.5 18.2 28.6 45.5 28.6 78 0 74.1-57.2 114.4-163.8 114.4-85.8 0-165.1-19.5-223.6-78l-117 117c91 92.3 197.6 122.2 338 122.2 193.7 0 343.2-101.4 343.2-280.8z"/>
          	<path id="HLSTATSZ" class="s1" aria-label="HLSTATSZ"  d="m8460.4 1464v-161.2h-396.5l396.5-621.4v-143h-591.5v161.2h378.3l-395.2 618.8v145.6z"/>
          </svg>
      </a>

      <nav class="hlstats-topnav">
        <a class="hlstats-navlink<?php echo active(['contents'], $currentMode); ?>" href="<?= $g_options['scripturl'] ?>">CONTENTS</a>
        <?php
        if ($g_options['sourcebans_address']) {
          echo '<a class="hlstats-navlink" href="'. $g_options['sourcebans_address'] . '" target="_blank">SOURCEBANS</a></li>';
        }
        if ($g_options['forum_address']) {
          echo '<a class="hlstats-navlink" href="' . $g_options['forum_address'] . '">FORUM</a>';
        }
        ?>
        <a class="hlstats-navlink<?php echo active(['help'], $currentMode); ?>" href="<?= $g_options['scripturl'] ?>?mode=help">HELP</a>
      </nav>
      <div class="hlstats-topright">
        <div class="hlstats-login"><?= $signin ?></div>
      </div>
    </div>
  </div>

  <!-- SUB BAR -->
  <div class="hlstats-sub">
    <div class="hlstats-inner">
<?php
    if (!empty($_GET) && !empty($game) && $mode != 'admin' && $mode != 'help') { 

      $gameName=!empty($_SESSION['realname']) ? htmlspecialchars($_SESSION['realname']) : 'Servers';
?>
      <nav class="hlstats-subnav">
        <div class="hlstats-dropdown hlstats-game-dropdown" id="game-dropdown">
          <a href="?game=<?= $game ?>" class="hlstats-server hlstats-game-link"><?= $gameName ?></a>
          <button class="hlstats-dropbtn hlstats-game-btn"
                  type="button"
                  aria-haspopup="true"
                  aria-expanded="false">
            <span class="hlstats-game-hamburger">&#9776;</span>
            <span class="hlstats-server"><?= $gameName ?></span><span class="caret">&#9660;</span>
          </button>
          <div class="hlstats-dropmenu">
            <a href="?game=<?= $game ?>" class="hlstats-server" title="<?= $gameName ?> Servers"><?= $gameName ?></a>
            <ul id="gamelist-menu"></ul>
          </div>
        </div>
        <a href="?mode=players&amp;game=<?= $game ?>">Players</a>
            <a href="?mode=clans&amp;game=<?= $game ?>">Clans</a>
        <a href="?mode=awards&amp;game=<?= $game ?>">Awards</a>

        <div class="hlstats-dropdown">
          <button class="hlstats-dropbtn"
                  type="button"
                  aria-haspopup="true"
                  aria-expanded="false">
            Sections <span class="caret">&#9660;</span>
          </button>

          <div class="hlstats-dropmenu">
           <?php if ($g_options['nav_globalchat']==1) { ?>
              <a href="?mode=chat&amp;game=<?= $game ?>">Chat</a>
            <?php } ?>
            <a href="?mode=actions&amp;game=<?= $game ?>">Actions</a>
            <a href="?mode=weapons&amp;game=<?= $game ?>">Weapons</a>
            <a href="?mode=maps&amp;game=<?= $game ?>">Maps</a>
            <?php
            $db_game = $db->escape($game);
            $result = $db->query("SELECT game from hlstats_Roles WHERE game='$db_game' AND hidden = '0'");
            $numitems = $db->num_rows($result);
            if ($numitems > 0) {
            ?>
                <a href="?mode=roles&amp;game=<?= $game ?>">Roles</a>
            <?php } ?>
            <?php if ($g_options['nav_cheaters']==1) { ?>
              <a href="?mode=bans&amp;game=<?= $game ?>">Bans</a>
            <?php } ?>
            <?php if ($g_options['countrydata']) { ?>
              <a href="?mode=countryclans&amp;game=<?= $game ?>">Countries</a>
            <?php } ?>

          </div>
        </div>

      </nav>

<?php } ?>

      <div class="hlstats-header-right">
<?php if ($mode !== 'admin') { ?>
      <div class="hlstats-header-search" id="hlstats-search">
        <form class="hlstats-form" method="get" action="<?= $g_options['scripturl'] ?>">
          <input type="hidden" name="mode" value="search" />
      
          <input id="hlstatsSearchQ" type="text" name="q" placeholder="Find a player" autocomplete="off" />
          <button id="hlstatsSearchSubmit" class="search svg" type="submit" aria-label="Search">
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18" fill="none" aria-label="Search"><path fill="currentColor" d="M13.8296 12.0786C14.8347 10.6321 15.2623 8.86133 15.0284 7.11496C14.7945 5.36859 13.9159 3.77313 12.5656 2.64269C11.2153 1.51224 9.49114 0.928708 7.73254 1.00696C5.97394 1.08522 4.30831 1.8196 3.06357 3.06552C1.81882 4.31144 1.08514 5.97864 1.00696 7.7389C0.928776 9.49916 1.51176 11.2249 2.64114 12.5765C3.77052 13.9281 5.36446 14.8075 7.10919 15.0417C8.85391 15.2758 10.623 14.8477 12.0682 13.8417L15.2185 17L15.3997 16.8187L16.8188 15.3982L17 15.2168L13.8296 12.0786ZM8.04222 12.5824C7.14643 12.5824 6.27075 12.3165 5.52593 11.8183C4.7811 11.3202 4.20058 10.6122 3.85777 9.78376C3.51497 8.95538 3.42528 8.04384 3.60004 7.16443C3.7748 6.28502 4.20616 5.47723 4.83958 4.84321C5.47301 4.20919 6.28004 3.77742 7.15862 3.60249C8.0372 3.42757 8.94787 3.51734 9.77548 3.86047C10.6031 4.2036 11.3104 4.78467 11.8081 5.5302C12.3058 6.27573 12.5714 7.15223 12.5714 8.04887C12.5714 9.25123 12.0943 10.4043 11.2449 11.2545C10.3955 12.1047 9.24344 12.5824 8.04222 12.5824V12.5824Z"></path></svg>
          </button>
      
          <div id="hlstatsSearchPanel" class="hlstats-search-panel">
            <?php
              $search->drawForm(array('mode' => 'search'), -1, 'header');
            ?>
          </div>
        </form>
      </div>
<?php }
  if ($g_options['display_style_selector'] == 1) { ?>
      <div class="theme-switcher">
  <button class="theme-btn svg" aria-haspopup="true">
<svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M16.65 3.85938H7.35C3.25 3.85938 2 5.10938 2 9.20938V14.7894C2 18.8894 3.25 20.1394 7.35 20.1394H16.65C20.75 20.1394 22 18.8894 22 14.7894V9.20938C22 5.10938 20.75 3.85938 16.65 3.85938ZM14.09 13.1194C14.09 15.3694 13.04 16.4194 10.79 16.4194H8.56C6.31 16.4194 5.26 15.3694 5.26 13.1194V10.8894C5.26 8.63938 6.31 7.58938 8.56 7.58938H10.79C13.04 7.58938 14.09 8.63938 14.09 10.8894V13.1194Z" fill="currentColor"/>
</svg>
  </button>
  <div class="theme-menu" id="theme-menu"></div>
      </div>
<?php } 
$baseUrl = $_SERVER['PHP_SELF'];
?>
      </div>
      <script>
      (() => {
        const root  = document.getElementById('hlstats-search');
        const input = document.getElementById('hlstatsSearchQ');
        const panel = document.getElementById('hlstatsSearchPanel');

        let last_q    = '';
        let last_st   = '';
        let last_game = '';

        if (!root || !input || !panel) return;
      
        const open = () => root.classList.add('is-open');
        const close = () => root.classList.remove('is-open');
      
        input.addEventListener('focus', open);
        input.addEventListener('click', open);
      
        document.addEventListener('click', (e) => {
          if (!root.contains(e.target)) close();
        });

        document.addEventListener('keydown', (e) => {
          if (e.key === 'Escape') close();
        });

        const submitElement = document.getElementById('hlstatsSearchSubmit');

        submitElement.addEventListener('click', function (e) {
            e.preventDefault();

            let q=input.value;
            let st=document.getElementsByName('st')[0].value;
            let game=document.getElementsByName('game')[0].value;

            if (!input.value.trim()) return false;
            if (q == last_q && st == last_st &&  game == last_game) return false;
            last_q    = q;
            last_st   = st;
            last_game = game;

            const params = new URLSearchParams({ mode: 'search', ajax: 'search', q, st, game });
            Fetch.run('<?=$baseUrl?>?' + params.toString(), 'hlstats-contents');
        });

      })();
      </script>
    </div>
  </div>
</div>

<div id="hlstats-contents" class="hlstats-contents <?=$mode?>">
<?php
$bannerSrc = '';
if (!empty($g_options['bannerfile']) && $g_options['bannerdisplay'] != 0 && ($mode == 'contents' || $g_options['bannerdisplay']==1)) {
    if (preg_match('/^https?:\/\//i', $g_options['bannerfile']) && filter_var($g_options['bannerfile'], FILTER_VALIDATE_URL)) {
        $bannerSrc = $g_options['bannerfile'];
    } else {
        $bannerSrc = IMAGE_PATH . '/' . basename($g_options['bannerfile']);
    }

    if ($bannerSrc !== '') {
    ?>    
        <div class="hlstats-banner">
            <img src="<?php echo htmlspecialchars($bannerSrc, ENT_QUOTES, 'UTF-8'); ?>" alt="Banner" />
        </div>
     <?php
    }
}
?> 